<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pets', function (Blueprint $table) {
            $table->id('PetID');
            $table->unsignedBigInteger('ClientID');
            $table->unsignedBigInteger('AccountID');
            $table->unsignedBigInteger('VetID')->nullable();
            $table->boolean('Past');
            $table->text('PrimarySitterFirstName');
            $table->text('PrimarySitterLastName');
            $table->text('PetPhoto');
            $table->text('Name');
            $table->text('Type');
            $table->text('Breed');
            $table->text('Colour');
            $table->text('Weight');
            $table->text('Gender');
            $table->text('Spayed');
            $table->text('Neutered');
            $table->text('NeuteredNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->date('DateOfBirth')->nullable();
            $table->boolean('DOBEstimated');
            $table->text('Microchipped');
            $table->bigInteger('ChipNumber')->nullable();
            $table->text('Insured');
            $table->text('InurancePolicy');
            $table->boolean('PassedAway');
            $table->text('FitnessLevel');
            $table->text('HealthConcerns')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Allergies');
            $table->text('AllergiesNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Disabilities');
            $table->text('DisabilitiesNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Illnesses');
            $table->text('IllnessesNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('FeedingInstructions')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('LocationFood')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('FoodImage');
            $table->boolean('HotelFeedTimeAM');
            $table->boolean('HotelFeedTimeMid');
            $table->boolean('HotelFeedTimePM');
            $table->text('CurrentMedication');
            $table->text('MedicationNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('MedicationImage');
            $table->text('PetNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('ClientPetNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->date('Incident1Date')->nullable();
            $table->text('Incident1Type');
            $table->text('Incident1Severity');
            $table->text('Incident1Desc')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Incident1Picture');
            $table->text('Incident1Form');
            $table->text('Incident1StaffInstructions')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Incident1ReportingStaff');
            $table->text('Incident1ManagementDec')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('AddIncident');
            $table->date('Incident2Date')->nullable();
            $table->text('PermWalkOfflead');
            $table->text('PermOffleadEnviro');
            $table->text('BittenPeople');
            $table->text('BittenPeopleInfo');
            $table->text('Aggression');
            $table->text('AggressionInfo');
            $table->text('BittenDogs');
            $table->text('BittenDogsInfo');
            $table->text('DogAgression');
            $table->text('DogAgressionInfo');
            $table->text('DogSocial');
            $table->text('DogRecall')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogFears')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogPulls');
            $table->text('DogPullsInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogSlipCollar');
            $table->text('DogSlipCollarInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogChase');
            $table->text('DogChaseInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogMobility');
            $table->text('DogMobilityInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogCarSick');
            $table->text('DogCarSickInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogHidingPlace');
            $table->text('DogHidingPlaceInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Muzzled');
            $table->text('MuzzledInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogWalkOtherInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('BoardOtherDogs');
            $table->text('BoardOtherDogsInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('BoardOtherCats');
            $table->text('BoardOtherCatsInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('BoardOtherChildren');
            $table->text('BoardOtherChildrenInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->boolean('RequireBoardingService');
            $table->text('DogSleepLocation')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogSpecialNeeds');
            $table->text('DogSpecialNeedsInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('WalkFreq')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogFearsHome')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogFearsHomeInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogChew')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogChewInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('FoodAgression')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('FoodAgressionInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('HouseTrained')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('HouseTrainedInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('ExcessiveBarking')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('ExcessiveBarkingInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('SeparationAnx')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('SeparationAnxInfo')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('AllowedOnFurniture')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('AllowedUpstairs')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('AllowedOnBeds')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('DogDigging')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('CrateTrained')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('UsualWakeTime')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('UsualBedTime')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('Vac1');
            $table->date('Vac1Date')->nullable();
            $table->text('Vac1Cert');
            $table->boolean('AddVac2');
            $table->text('Vac2');
            $table->date('Vac2Date')->nullable();
            $table->text('Vac2Cert');
            $table->boolean('AddVac3');
            $table->text('Vac3');
            $table->date('Vac3Date')->nullable();
            $table->text('Vac3Cert');
            $table->boolean('AddVac4');
            $table->text('Vac4');
            $table->date('Vac4Date')->nullable();
            $table->text('Vac4Cert');
            $table->text('GroomingNotes')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('GroomingTime')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('GroomingPhoto');
            $table->text('GroomingOwnerSpecifics')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('GroomingPriceCharged')->charset('utf8mb4')->collation('utf8mb4_unicode_ci');
            $table->text('GroomingTandCs');
            $table->text('XLBullyExemption');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pets');
    }
};
