<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
        'ClientID',
        'AccountID',
        'Status',
        'InvoiceType',
        'PrimaryStaffID',
        'StaffFirstName',
        'StaffLastName',
        'TeamID',
        'TeamMembers',
        'Area',
        'Type',
        'DiaryRef',
        'FirstName',
        'LastName',
        'Email',
        'HomePhone',
        'WorkPhone',
        'MobilePhone',
        'Address1',
        'Address2',
        'Address3',
        'AddressTown',
        'AddressState',
        'AddressZip',
        'Run',
        'AltFirstName',
        'AltLastName',
        'AltRelationship',
        'AltEmail',
        'AltCCEmail',
        'AltHomePhone',
        'AltWorkPhone',
        'AltMobilePhone',
        'AltAddress1',
        'AltAddress2',
        'AltAddress3',
        'AltAddressTown',
        'AltAddressState',
        'AltAddressZip',
        'AltKeyHolder',
        'AccessDoorImage',
        'LockBoxCodeAndLocation',
        'LockBoxImage',
        'Alarmed',
        'AlarmInstructions',
        'AlarmImage',
        'KDWhasKey',
        'ParkingSpaceImage',
        'BuildingAccessInstructions',
        'AccessKey',
        'WalkInfoPhoto',
        'WalkInfoKeySafeInstructions',
        'WalkInfoDogLeft',
        'WalkInfoWalkingInfo',
        'WalkInfoFeedingInfo',
        'WalkInfoWalkWithOthers',
        'WalkInfoHarnessPhoto',
        'WalkInfoImportantInfo',
        'What3Words',
        'WalkInfoExtraPhoto1',
        'WalkInfoExtraPhoto2',
        'AdminNotes',
        'StaffNotes',
        'Emg1FirstName',
        'Emg1LastName',
        'Emg1Relationship',
        'Emg1Email',
        'Emg1CCEmail',
        'Emg1HomePhone',
        'Emg1WorkPhone',
        'Emg1MobilePhone',
        'Emg1Address1',
        'Emg1Address2',
        'Emg1Address3',
        'Emg1AddressTown',
        'Emg1AddressState',
        'Emg1AddressZip',
        'Emg1KeyHolder',
        'Emg1Notes',
        'Emg2FirstName',
        'Emg2LastName',
        'Emg2Relationship',
        'Emg2Email',
        'Emg2HomePhone',
        'Emg2WorkPhone',
        'Emg2MobilePhone',
        'Emg2Address1',
        'Emg2Address2',
        'Emg2Address3',
        'Emg2AddressTown',
        'Emg2AddressState',
        'Emg2AddressZip',
        'Emg2KeyHolder',
        'Emg2Notes',
        'Emg3FirstName',
        'Emg3LastName',
        'Emg3Relationship',
        'Emg3Email',
        'Emg3HomePhone',
        'Emg3WorkPhone',
        'Emg3MobilePhone',
        'Emg3Address1',
        'Emg3Address2',
        'Emg3Address3',
        'Emg3AddressTown',
        'Emg3AddressState',
        'Emg3AddressZip',
        'Emg3KeyHolder',
        'Emg3Notes',
        'RequirePickDrop',
        'PickupInstructions',
        'DropOffInstructions',
        'WetInstructions',
        'BringInMail',
        'MailInstructions',
        'BringInNewspaper',
        'NewspaperInstructions',
        'TakeOutRubbish',
        'RubbishInstructions',
        'WaterIndoorPlants',
        'IndoorPlantInstructions',
        'WaterOutdoorPlants',
        'OutdoorPlantInstructions',
        'AdjustAC',
        'ACInstructions',
        'AdjustLights',
        'LightsInstructions',
        'AdjustCurtains',
        'CurtainInstructions',
        'OtherInstructions',
        'OtherHouseSitInstructions',
        'DocsClientReg',
        'DocsDaycareTaCs',
        'DocsOffleadTaCs',
        'DocsWalksTaCs',
        'DocsBoardingTaCs',
        'DocsGroomingTaCs',
        'DocsOLDTaCs',
        'DocsClientCareTaCs',
        'DocsDogAssessTaCs',
        'DocsOtherNameTaCs',
        'DocsOtherTaCs',
        'PrefPaymentMethod',
        'ChargeCardOnFile',
        'BillingNotes',
        'BillingType',

        // Add all other column names you wish to be mass-assignable
    ];




}
